### ISSUE TITLE
[Dashboard] Show user statistics and progression

### ISSUE THREAD

**Issue by pnxdxt** [chesspecker/frontend#17]

**Comment by t1u1** [comment]
I am not sure what this issue is exactly about. But I would like to see progress of the currently open session in the dashboard.

Currently, the progress is only visible while the session is running, but during the session, the timer is running and eyes are focused on the puzzle, so I usually miss the progress done.

It would be also nice to see an Estimated completion time, based on the currently consumed time and progress. For example, if I have finished 50% of the puzzles and taken 30 minutes, then Estimated completion time would be 60 minutes. Could be shown on hover, to reduce clutter.

PS. Thanks for adding the keyboard shortcuts so quickly! :heart_eyes:

**Comment by pnxdxt** [comment]
Moved to https://github.com/chesspecker/chesspecker/issues/6
