### ISSUE TITLE
Validation when creating a set

### ISSUE THREAD

**Issue by Sailias** [chesspecker/frontend#76]
You are able to create a set without any phases selected which results in starting a set without any puzzles being served.

If you make "Healthy Mix" selected by default, that will ensure that all sets have a phase selection.
I would also add server side validation as well.

**Comment by pnxdxt** [comment]
@henribruvier I patched this issue quickly I'm leaving the issue open because I think we can do better than the quick workaround I made in https://github.com/chesspecker/frontend/commit/8ef58edd0b8089bedcf033a001eca1d47a55a960

Better issue handling would be making "Healthy Mix" selected when nothing else is selected.

**Comment by henribruvier** [comment]
good work @pnxdxt
